### ISSUE TITLE
error json

### ISSUE THREAD

**Issue by DenDeze** [flozz/p0wny-shell#10]
Error while parsing response: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data popup firefox

**Comment by ndoell** [comment]
> Error while parsing response: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data popup firefox

Same issue here.

**Comment by pxlrbt** [comment]
Check the response in the network tab of your developer tools. This is probably the result of a PHP warning/error, e.g. when `exec()` is disabled.

**Comment by flozz** [comment]
I close this issue as it is inactive :)
