### ISSUE TITLE
thanks i hacked my school with it xD

### ISSUE THREAD

**Issue by getgle** [flozz/p0wny-shell#19]
everyone thinks im a hacker now lol.  i guess i really am

**Comment by flozz** [comment]
You should not be proud of that... And maybe you should read the definition of [script kiddie](https://en.m.wikipedia.org/wiki/Script_kiddie) 🙄

**Comment by getgle** [comment]
why release hacking tools if you dont want people to hack with them?? LOL

**Comment by flozz** [comment]
For the same reason we produce knifes. p0wny@shell is a tool for infosec researchers, but of course some people will do bad things with it.

If you want to read more about my opinion on this, read my blog post: 

* https://translate.google.com/translate?sl=auto&tl=en&text&u=https%3A%2F%2Fblog.flozz.fr%2F2020%2F01%2F21%2Fp0wny-shell-un-shell-php-simple-mais-trop-efficace%2F

And before pretending being a "hacker", write your own tools and fix the security issues on your own website ;)

**Comment by getgle** [comment]
i am a hacker.  i hacked my school xD
