### ISSUE TITLE
for remote server

### ISSUE THREAD

**Issue by irulvam** [flozz/p0wny-shell#3]
can you make it use for remote server. so i can place it in external server and i can remote with this to internal server

**Comment by flozz** [comment]
Hello,

This is out of the scope of this project, but you can easily tweak the shell to do what you want.

You can replace URLs in calls to the `makeRequest` function (lines like [this one](https://github.com/flozz/p0wny-shell/blob/master/shell.php#L197)) to point an other p0wny@shell script located on an other server:

```javascript
makeRequest("?feature=shell", ... )  // replace this
makeRequest("http://<SERVER_IP>/shell.php?feature=shell", ...)  // by this
```
