### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by cli-ish** [flozz/p0wny-shell#34]
It would be a cool little feature that allows the shell user to define a password/username for the shell to prevent unauthorized access to it.

I would implement it as follows:
1. add 3 new variables to SHELL_CONFIG: authentication_needed (bool), login_username (string), login_password (sha256 or md5 of the password).
2. if authentication_needed = true, then add a "WWW-Authenticate" header and exit().
3. check if the user's credentials are correct and let him in.

Is this something that can be implemented?

**Comment by flozz** [comment]
Hello,

I think this is outside of the scope of this project. p0wny@shell should only be used for pentesting and should not be used as an "everyday" shell nor to keep a rogue access to a server.

If someone really want to limit its access with a password, it can be done through the configuration of the HTTP server (vhost config for Nginx, vhost config or `.htaccess` / `.httpasswd` for Apache) but I do not want to make it a feature to not encourage wrong usages. :)
