### ISSUE TITLE
Non-Ascii Characters

### ISSUE THREAD

**Issue by godylockz** [flozz/p0wny-shell#39]
![image](https://github.com/flozz/p0wny-shell/assets/81207744/95ee5593-11ad-4462-913c-7e0d17b81f98)

Found non-ASCII characters in the UI during file upload. Would replace to ASCII equivalence.

Current:
![image](https://github.com/flozz/p0wny-shell/assets/81207744/87e80864-1ac0-4eba-9d8f-6538d080da09)

After:
![image](https://github.com/flozz/p0wny-shell/assets/81207744/231caf0f-46de-4eef-a7dc-e4ee56ca2a87)

**Comment by flozz** [comment]
it seems to be a simple encoding issue (probably wrong encoding sent in the headers by the http server. Forcing encoding to utf-8 may work.

I close this issue as it is not a p0wny shell bug :)
