### ISSUE TITLE
Add username@hostname

### ISSUE THREAD

**Issue by adrianbj** [flozz/p0wny-shell#7]
@flozz - what do you think about implementing this: 
 
![image](https://user-images.githubusercontent.com/871211/54407636-d5104800-469b-11e9-8100-3644398cccff.png)

That screenshot shows how it looks using https://github.com/Arrexel/phpbash

If you're interested, I could put together a PR.

**Comment by flozz** [comment]
Please do, but it should work on windows too ;)

**Comment by unkn0wnsyst3m** [comment]
Please do!  if on windows, it should just be "whoami" intsead of "whoami"@"hostname"

**Comment by cli-ish** [comment]
I would try to implement this feature, but I have a few questions before I start:

Is this just a one-time read of the current user/group?
Or does this information need to be passed every time the user executes a command?

**Comment by flozz** [comment]
I think this can be query once when the page is loaded. It is very unlikely that the information change during the use of the terminal. I just do not know if it is very useful as most of the time the user will be `www-data` on Linux. :)

**Comment by cli-ish** [comment]
Then I'll create a PR about it, even if it's just a small feature, it's a nice gimmick.

**Comment by flozz** [comment]
Implemented in **v2023.05.22** :)
